[default.deploy.parameters]
stack_name = "demo-registry-stack"
resolve_s3 = true
s3_prefix = "demo-registry"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
